name: quel_prof
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.de

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^1.2.2
  share_plus: ^7.2.2
#  paged_vertical_calendar: ^1.1.4
  intl: ^0.19.0
  motion_toast: ^2.3.2
  getwidget: ^4.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  provider: ^6.0.3
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  flutter_snake_navigationbar: ^0.6.1
  paged_vertical_calendar: ^1.1.4
  firebase_auth: ^4.16.0
  flutter_session_manager: ^1.0.3
  cloud_firestore: ^4.14.0
  flutter_firebase_chat_core: ^1.6.3
  any_link_preview: ^3.0.2
  url_launcher: ^6.1.6
  flutter_keyboard_visibility: ^6.0.0
  webview_flutter: ^4.8.0
#  flutter_launcher_icons: ^0.10.0
#
#flutter_icons:
#  android: true
#  ios: true
#  remove_alpha_ios: true
#  image_path: "Assets/launch_icon/Group 178@2x.png"
#  adaptive_icon_background: "#2b2223"
#  #  adaptive_icon_foreground: "Assets/launch_icon/playstore.png"
#  min_sdk_android: 19 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "Assets/launch_icon/Group 178@2x.png"
#    adaptive_icon_foreground: "Assets/launch_icon/playstore.png"
#  #    background_color: "#hexcode"
#  #    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "Assets/launch_icon/Group 178@2x.png"
#    adaptive_icon_foreground: "Assets/launch_icon/playstore.png"
#    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - Assets/Icons/Vector(1).svg
    - Assets/Icons/calendar(1).svg
    - Assets/Icons/notification.svg
    - Assets/Icons/setting-2(1).svg
    - Assets/Icons/search-normal.svg
    - Assets/Icons/vuesax-bold-moon.svg
    - Assets/Icons/arrow-circle-left.svg
    - Assets/Icons/arrow-circle-right.svg
    - Assets/Icons/vuesax-linear-export.svg
    - Assets/Icons/vuesax-linear-arrow-left.svg
    - Assets/Icons/vuesax-linear-book-saved.svg
    - Assets/Icons/vuesax-linear-maximize-4.svg
    - Assets/Icons/_Glyphs - Quick Action - Book.svg
    - Assets/Icons/book.svg
    - Assets/Icons/moon.svg
    - Assets/Icons/heart.svg
    - Assets/Icons/timer.svg
    - Assets/Icons/trash.svg
    - Assets/Icons/export.svg
    - Assets/Icons/global.svg
    - Assets/Icons/Vector.svg
    - Assets/Icons/book(1).svg
    - Assets/Icons/Group 8.svg
    - Assets/Icons/calendar.svg
    - Assets/Icons/Group 26.svg
    - Assets/Icons/Group 83.svg
    - Assets/Icons/heart(1).svg
    - Assets/Icons/timer(1).svg
    - Assets/Icons/global(1).svg
    - Assets/Icons/Group 139.svg
    - Assets/Icons/Path 3684.svg
    - Assets/Icons/setting-2.svg
    - Assets/Images/crossError.png
    - Assets/Images/crossLight.png
    - Assets/Images/image1.png
    - Assets/Images/crossDark.png
    - Assets/launch_icon/167d298c-cef9-4317-b600-d8da249d4d2b.png
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
