// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgybZMHFzugLnewI0Ft4Id0Ohrlx_4YMo',
    appId: '1:241839977820:web:a2b80543effc85e43afd99',
    messagingSenderId: '241839977820',
    projectId: 'quel-prof',
    authDomain: 'quel-prof.firebaseapp.com',
    storageBucket: 'quel-prof.appspot.com',
    measurementId: 'G-Q7DFDXQRZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfubppDbFn8kTJlMoK5dhVpzmc4ZlVBQ',
    appId: '1:241839977820:android:80dd434a37e286fa3afd99',
    messagingSenderId: '241839977820',
    projectId: 'quel-prof',
    storageBucket: 'quel-prof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn3LsELdxc5AXz6I1uGyzlskDDDWiTB1k',
    appId: '1:241839977820:ios:8c35ccce856e34653afd99',
    messagingSenderId: '241839977820',
    projectId: 'quel-prof',
    storageBucket: 'quel-prof.appspot.com',
    iosClientId: '241839977820-i3us00bvuqlupomsf89fs2m7dfrjfpfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.quelProf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn3LsELdxc5AXz6I1uGyzlskDDDWiTB1k',
    appId: '1:241839977820:ios:8c35ccce856e34653afd99',
    messagingSenderId: '241839977820',
    projectId: 'quel-prof',
    storageBucket: 'quel-prof.appspot.com',
    iosClientId: '241839977820-i3us00bvuqlupomsf89fs2m7dfrjfpfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.quelProf',
  );
}
